import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '@/styles/Index.module.css';
import NavBar from '../components/NavBar';
import SearchBar from '../components/SearchBar';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Repos - Um repositório de trabalhos acadêmicos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
       
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Spectral:wght@400;500;700&display=swap" rel="stylesheet"/>


      </Head>
      <main className={'bg-night-300 text-snow-100 p-[20px]'}>
        <NavBar />
        <h1 className={'text-3xl text-[32px] mt-16 font-serif'}>
          Olá, o que vamos pesquisar hoje?
        </h1>
        <SearchBar />
      </main>
    </>
  );
}
